### ISSUE TITLE
Process a login

### ISSUE THREAD

**Issue by bwinkler-sigsci** [signalsciences/waf-testing-framework#1]
Some test environments are behind a login prompt. It would be good to have the ability to send login creds for those env. 

I believe Burp Suite has the ability to do this.

**Comment by alewinter-sigsci** [comment]
This is not a planned feature because it is out of scope of the current purpose of this framework.

The framework is designed to exercise only the WAF and not the application. The only requirement from an application perspective is that it exists and can handle GET and POST requests. The framework is not meant to be a tool used to crawl through an application and test form inputs and other interactive components. We are only trying to test the WAF and not the application.

If this becomes additional functionality that is highly requested over time we are happy to revisit.
